language: r
r: 
  - 3.6.2
  
sudo: required

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "renv::restore()"
  
script:
  - Rscript -e "source('run.R')"
  
deploy:
  provider: releases
  api_key: "$GITHUB_AUTH"
  file_glob: true
  file: outputs/*
  skip_cleanup: true
  on: 
    branch: master